CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT ,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    TOKEN VARCHAR(36),
    BIO VARCHAR(256),
    AVATAR_URL VARCHAR(100),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    CONSTRAINT USER_PK
		PRIMARY KEY (ID)
);